### ISSUE TITLE
FileUpload doesn't work

### ISSUE THREAD

**Issue by wgebis** [juanpablo-santos/stripes-spring-boot#5]
Hello,

it's very nice project :) 

But unfortunately file upload doesn't work with default `Multipart` impl (`servlets.com/com`) as well as with the `commons-fileupload` library :(.

```
java.io.IOException: Corrupt form data: premature ending
	at com.oreilly.servlet.multipart.MultipartParser.<init>(MultipartParser.java:205) ~[cos-05Nov2002.jar:na]
	at com.oreilly.servlet.MultipartRequest.<init>(MultipartRequest.java:222) ~[cos-05Nov2002.jar:na]
	at net.sourceforge.stripes.controller.multipart.CosMultipartWrapper.build(CosMultipartWrapper.java:98) ~[stripes-1.7.0-beta4.jar:1.7.0-beta4]
	at net.sourceforge.stripes.controller.multipart.DefaultMultipartWrapperFactory.wrap(DefaultMultipartWrapperFactory.java:161) ~[stripes-1.7.0-beta4.jar:1.7.0-beta4]
	at net.sourceforge.stripes.controller.multipart.DefaultMultipartWrapperFactory.wrap(DefaultMultipartWrapperFactory.java:37) ~[stripes-1.7.0-beta4.jar:1.7.0-beta4]
	at net.sourceforge.stripes.controller.StripesRequestWrapper.constructMultipartWrapper(StripesRequestWrapper.java:155) ~[stripes-1.7.0-beta4.jar:1.7.0-beta4]
	at net.sourceforge.stripes.controller.StripesRequestWrapper.<init>(StripesRequestWrapper.java:125) ~[stripes-1.7.0-beta4.jar:1.7.0-beta4]
	at net.sourceforge.stripes.controller.StripesFilter.wrapRequest(StripesFilter.java:242) ~[stripes-1.7.0-beta4.jar:1.7.0-beta4]
```

Any idea what is going on? 

Cheers,
W

**Comment by juanpablo-santos** [comment]
Hi @wgebis thanks for your kind words :-)

regarding the exception, it seems to be related to the cos library itself, not to the starter, check _Why when using com.oreilly.servlet.MultipartRequest or MultipartParser am I getting an IOException saying "Corrupt form data: premature ending" or "Separation boundary was not specified"?_ at http://www.servlets.com/cos/faq.html (it's roughly at the middle). Googling the exception also seems to indicate that the file size seems to be too big for the MultipartParser

In fact you should be able to reproduce the same bug using a simple Stripes application, the starter just takes care of instantiating the Stripes filter from your application's properties (or using Stripes default values if absent) and a few more beans, but it doesn't alter Stripes behaviour in any way

HTH,
juan pablo

**Comment by wgebis** [comment]
Hi, 
an alternative multipart impl also doesn’t work. It’s probably related to web server configuration, stripes server dispatcher seems to be not used in spring boot app. Post binary data is not available at the parsing time. Sample app doesn’t work as well. 
😔

**Comment by juanpablo-santos** [comment]
Hi @wgebis ,

uploaded a working sample of file uploads; turns out it was needed to explicit `spring.servlet.multipart.enabled=false` on the `application.properties` file so the attachment is able to reach the Stripes ActionBean. Also added a small section on the README file explaining that, and while at it also upgraded the starter to use latest Spring Boot and tagged it.

HTH,
juan pablo
